### PR TITLE
Create a GitHub Actions alternative to Travis CI

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/sivy/pystatsd/actions
https://github.com/cclauss/pystatsd/actions

### CODE REVIEW

**Comment by cclauss** [comment]
```
Run nosetests tests
.....E..
======================================================================
ERROR: test_basic_client_update_stats_multi (tests.transplant_class.<locals>.C)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pystatsd/pystatsd/tests/client.py", line 83, in test_basic_client_update_stats_multi
    self.mock_socket.return_value.sendto.assert_call_any(
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/mock/mock.py", line 637, in __getattr__
    raise AttributeError("Attributes cannot start with 'assert' "
AttributeError: Attributes cannot start with 'assert' or 'assret'

----------------------------------------------------------------------
Ran 8 tests in 0.052s
```

**Review by sivy — APPROVED** [review]
👍

**Comment by sivy** [comment]
@cclauss I think a move to github actions might be good, I tried to get things working with travis and it's not recognizing the repo there.

**Comment by cclauss** [comment]
I get `AttributeError: Attributes cannot start with 'assert' or 'assret'` on both Python 2 and 3 but do not know how to fix that issue.

**Comment by sivy** [comment]
@cclauss I don't see "assret" anywhere in your branch or this repo, so I cannot be sure where it's coming from. Is there a log somewhere I can see? (Also working $dayjob so I will not be able to respond quickly for a while)

**Comment by cclauss** [comment]
pystatsd/tests/client.py", line 83

**Comment by cclauss** [comment]
https://github.com/cclauss/pystatsd/runs/453299837?check_suite_focus=true#step:9:11

**Comment by sivy** [comment]
looks like this is not vali anymore:

`self.mock_socket.return_value.sendto.assert_call_any`

**Comment by cclauss** [comment]
I think we will have the same problem with `assert_call_with()` too.

**Comment by sivy** [comment]
if you get it building I'll merge and then we can move on. if it all works, remove the travis config file too. Thanks!

**Comment by sivy** [comment]
You ready for merge?

**Comment by cclauss** [comment]
Yes.

**Comment by sivy** [comment]
👍

**Comment by sivy** [comment]
image

Build happening!

**Comment by sivy** [comment]
What are your plans for the actions? are artifacts for pypi going to get built here?

**Comment by cclauss** [comment]
I use Actions for testing and have never used them to deploy to PyPI.

**Pull request merged**
